development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: vae-survey31_development
  pool: 5
  username: root
  password: projecte
  host: localhost
  port: 5435

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: vae-survey31_test
  pool: 5
  username: root
  password: projecte
  host: localhost
  port: 5435

production:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: vae-survey31_production
  pool: 5
  username: root
  password: projecte
  host: localhost
  port: 5435

mssql:
  adapter: sqlserver
  mode: odbc
  dsn: SQL_SERVER
  username: rails_survey
  password: kepler1983
  host: localhost
  pool: 256
  timeout: 10000
